spring:
  profiles: default
  application:
    name: food-truck

#logging.pattern.level=%d{ABSOLUTE} [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n
#logging.level.root=info
#logging.level.mcp.cloudtrace=info

server:
  port: 8082
  
services:
  produto:
    url: ${SERVICE_PRODUTO_URL:localhost:8080}  
  cliente:
    url: ${SERVICE_CLIENTE_URL:localhost:8081}  

# opentracing:
#   jaeger:
#     udp-sender:
#       host: jaeger
#       port: 6831

---

spring:
  profiles: dev
  application:
    name: food-truck

#logging.pattern.level=%d{ABSOLUTE} [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n
#logging.level.root=info
#logging.level.mcp.cloudtrace=info

server:
  port: 8082
  
services:
  produto:
    url: ${SERVICE_PRODUTO_URL:localhost:8080}  
  cliente:
    url: ${SERVICE_CLIENTE_URL:localhost:8081}  

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831