version: '3'
services:
  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - '7000:7000'
      - '9042:9042'
    # volumes:
    #   - 'cassandra_data:/bitnami'
    environment:
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=user
      - CASSANDRA_PASSWORD=jeager1
      - CASSANDRA_TRANSPORT_PORT_NUMBER=7000
      - CASSANDRA_CQL_PORT_NUMBER=9042
    networks:
      - jaeger            

  jeager:
    image: jaegertracing/all-in-one:1.18
    container_name: jaeger
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    command: ["--cassandra.span-store-write-cache-ttl=0h1m5s"]
    environment:
      - SPAN_STORAGE_TYPE=cassandra
      - CASSANDRA_SERVERS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=jeager_v1
      - CASSANDRA_USERNAME=user
      - CASSANDRA_PASSWORD=jeager1
      - CASSANDRA_SPAN_STORE_WRITE_CACHE_TTL=0h1m00s # --cassandra.span-store-write-cache-ttl=0h1m5s

      #- BADGER_SPAN_STORE_TTL=0h1m00s
      #- SPAN_STORAGE_TYPE=badger
      #- BADGER_EPHEMERAL=false
      #- BADGER_DIRECTORY_VALUE=/badger/data
      #- BADGER_DIRECTORY_KEY=/badger/key
    # volumes: 
    #   - /home/lirio/Workspace/jaeger:/badger
    depends_on:
    - cassandra         
    networks:
      - jaeger          

  # foodtruck:
  #   image: diegolirio/food-truck:0.0.1-SNAPSHOT
  #   container_name: foodtruck
  #   #restart: always
  #   ports:
  #     - 8082:8082
  #   environment:
  #     - SERVICE_CLIENTE_URL=cliente:8081
  #     - SERVICE_PRODUTO_URL=produto:8080
  # cliente:
  #   image: diegolirio/cliente:0.0.1-SNAPSHOT
  #   container_name: cliente
  #   #restart: always
  #   ports:
  #     - 8081:8081
  
  produto:
    image: diegolirio/produto:0.0.2-SNAPSHOT
    container_name: produto
    ports:
      - 8080:8080
    networks:
      - jaeger      
    environment:
      - JEAGER_AGENT=jeager
      - JEAGER_PORT=6831

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - 9090:9090
  #   command:
  #     - --config.file=/etc/prometheus/prometheus.yml
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   depends_on:
  #     - cliente

networks:
  jaeger:
    driver: bridge

#  sudo docker run -d --name jaeger \\n  -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \\n  -p 5775:5775/udp \\n  -p 6831:6831/udp \\n  -p 6832:6832/udp \\n  -p 5778:5778 \\n  -p 16686:16686 \\n  -p 14268:14268 \\n  -p 14250:14250 \\n  -p 9411:9411 \\n  jaegertracing/all-in-one:1.18
