version: '2'

services:
    jaeger-collector:
      image: jaegertracing/jaeger-collector
      container_name: jeager-collector
      command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411", "--cassandra.span-store-write-cache-ttl=0h1m5s"]
      ports:
        - "14269"
        - "14268:14268"
        - "14250"
        - "9411:9411"
      restart: on-failure
      #environment:
      #  - CASSANDRA_SPAN_STORE_WRITE_CACHE_TTL=0h1m00s # --cassandra.span-store-write-cache-ttl=0h1m5s

      depends_on:
        - cassandra-schema

    jaeger-query:
      image: jaegertracing/jaeger-query
      container_name: jeager-query
      command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
      ports:
        - "16686:16686"
        - "16687"
      restart: on-failure
      depends_on:
        - cassandra-schema

    jaeger-agent:
      image: jaegertracing/jaeger-agent
      container_name: jeager-agent
      command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
      restart: on-failure
      depends_on:
        - jaeger-collector

    cassandra:
      image: cassandra:3.9
      container_name: cassandra

    cassandra-schema:
      image: jaegertracing/jaeger-cassandra-schema
      container_name: cassandra-schema
      depends_on:
        - cassandra

    produto:
      image: diegolirio/produto:0.0.2-SNAPSHOT
      container_name: produto
      ports:
        - 8080:8080