spring:
  application:
    name: produto
    version: 1.0.0
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *

# TRACING-settings
#opentracing:
#  jaeger:
#    service-name: produto
#    enabled: TRUE
#    udp-sender:
#      host: localhost:6831

--- 
spring:
  profiles: dev

opentracing:
  jaeger:
    udp-sender:
      host: ${JEAGER_AGENT:jaeger-agent}
      port: 6831
